### ISSUE TITLE
Design change not possible

### ISSUE THREAD

**Issue by developdeez** [zsajjad/react-facebook-account-kit#11]
Is there a way to change design? I dont see any options in the docs for this.

**Comment by LukasUnbesiegt** [comment]
If you are telling account kit login design . you need to change that in facebook developer settings of account kit . you can't modify it by your own css .

**Comment by developdeez** [comment]
ok thx

**Comment by zsajjad** [comment]
https://developers.facebook.com/docs/accountkit/webjs/customizing
