### ISSUE TITLE
User details not receive in response 

### ISSUE THREAD

**Issue by sagarbagra** [zsajjad/react-facebook-account-kit#13]
how i get user details in response which are enter by user . i just receive only token and access token and i also want to get user mobile number or email which are enter by users.
please help me .

<AccountKit
                                    appId="11111111111111" // Update this!
                                    version="v1.0" // Version must be in form v{major}.{minor}
                                    onResponse={(resp) => console.log(resp)}
                                    csrf={'csrf token here!'} // Required for security
                                    countryCode={'+91'} // eg. +60
                                    debug={true}
                                    // loginType = "EMAIL"
                                    emailAddress={'abc@gmail.com'} // eg. me@site.com
                                  >
                                    {p => <a {...p} href="javascript:;" className="ragister-button">Ragister</a>}
                                  </AccountKit>

**Comment by zsajjad** [comment]
You can use API calls to get user info.
```
function fetchAccessToken(data) {
  return axios.get("https://graph.accountkit.com/v1.0/access_token", {
    params: {
      grant_type: configs.ACCOUNT_KIT_GRANT_TYPE,
      code: data.code,
      access_token: `AA|${configs.FACEBOOK_APP_ID}|${
        configs.ACCOUNT_KIT_APP_SECRET
      }`,
    },
  });
}

function fetchProfile(data) {
  return axios.get("https://graph.accountkit.com/v1.0/me", {
    params: {
      access_token: data.access_token,
    },
  });
}

```

**Comment by sagarbagra** [comment]
I just hit https://graph.accountkit.com/v1.0/access_token this api and i get this type response.Please help me i am new in react 

{
    "error": {
        "message": "Invalid OAuth 2.0 Access Token",
        "type": "EMApiException",
        "code": 190,
        "error_data": [],
        "fbtrace_id": "BC7mRhDMf00"
    }
}
