### ISSUE TITLE
Add default prop for number region/country

### ISSUE THREAD

**Issue by andela-cobiora** [zsajjad/react-facebook-account-kit#2]
Add a `default` phone number prop so that numbers can be set to a region. On mobile, a user has to scroll a lot for countries

![screen shot 2017-10-29 at 8 13 44 pm](https://user-images.githubusercontent.com/8373338/32147318-b42fb53a-bce5-11e7-9ae7-19203dea7d54.png)

**Comment by zsajjad** [comment]
Fixed in #3

**Comment by ralfpatric** [comment]
I tried adding the countryCode but it doesn't work for me. Any chance it broke over time or am I doing smth wrong?

<AccountKit
              appId={this.props.appId} // Update this!
              version={this.props.version} // Version must be in form v{major}.{minor}
              onResponse={(resp) => {this.props.loginCallback(resp);}}
              csrf={this.props.token} // Required for security
              countryCode={'+45'} // eg. +60
            >
              {p => <button className="login-button" {...p}>LOG IN</button>}
            </AccountKit>

**Comment by d30jeff** [comment]
Have you tried passing in a `string`?

Based on [this](https://github.com/zsajjad/react-facebook-account-kit/blob/master/src/index.js#L90) prop definition. It's expecting a string.

**Comment by ralfpatric** [comment]
I tried passing it down as a string as well. I tried
countryCode="+45"
countryCode='+45'
countryCode={this.props.countryCode}
but nothing worked.

I've tried with other optional props and none of them work as a matter of fact. PhoneNumber, loginType, disabled, language, nothing :/ 

Even tried copy pasting the example provided and not even that is running the optional props. Any suggestions?

**Comment by d30jeff** [comment]
I've tried installing the package from npm and can confirm that it isn't working.
However the source code and the bundled source works fine.

@zsajjad Any idea what's going on?

**Comment by vivek9716** [comment]
@zsajjad, I am also stuck in this issue if this is fix let me know thanks.
