### ISSUE TITLE
Use in react native project

### ISSUE THREAD

**Issue by kkrishnan90** [zsajjad/react-facebook-account-kit#4]
Hi, this is more of a query than issue. Can we use this library in my react native project ? Will the same code work ?

**Comment by kkrishnan90** [comment]
I'm using expo to build my apps. So I would also like to know whether this library would be supported for the current development setup with expo that I use. Awaiting your response. Thanks in advance.

**Comment by zsajjad** [comment]
No this package is for web only. Please use [react-native-facebook-account-kit](https://github.com/underscopeio/react-native-facebook-account-kit).
